### ISSUE TITLE
Composing with other Generators

### ISSUE THREAD

**Issue by cmalven** [khalwat/generator-nystudio107#7]
Hey there, great generator. Very nice work.

Our company has our own Yeoman generator for configuring our standard frontend build, but it doesn't yet include automatic installation/configuration of Craft.

We would love to compose `generator-craftinstall` with our generator rather than build our own Craft-specific generator, but it isn't entirely clear how that integration would work.

Ideally, we'd do something like the following:
1. Add `generator-craftinstall` as a dependency in the `package.json` for our generator.
2. In the `index.js` for our `app` generator, compose `generator-craftinstall` using the [Yeoman standards for compassable generators](http://yeoman.io/authoring/composability.html) and passing in customized params for everything in `/app/templates/advanced_craft_install.json`

Something like…

``` js
installCraft: function() {
  this.composeWith('craftinstall', {
    "INSTALL_NAME": "One Base Custom Craft Install",
    "INSTALL_KEY": "one_base_custom_craft_install",
    "QUESTIONS": [
      {
          "name": this.props.projectName,
          "message": this.props.projectTitle,
          "default": "my-project"
      }
    ],

    …
  });
}
```

In lieu of that, do you have a suggestion for a nice way for our (or someone else's) generator to compose nicely with `generator-craftinstall` without forking the repo? Appreciate the help, and thanks for everything you're doing for the Craft community.

**Comment by khalwat** [comment]
I've actually never done this, but I'm interested in trying to figure out a good way for it to work.

**Comment by cmalven** [comment]
@khalwat I haven't actually done it either, but it seems like a nice idea and not _insanely_ difficult from what I've read. Let me know what I can do to help if you decide to do any work on it.
